In [1]:
import sys
from pathlib import Path

import pandas as pd
from imblearn.over_sampling import RandomOverSampler

sys.path.append(str(Path.cwd().parent / "src"))
from credit_risk import build_model, evaluate, split

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
lending_data_df = pd.read_csv("Resources/lending_data.csv")
lending_data_df.head()

,loan_size,interest_rate,borrower_income,debt_to_income,num_of_accounts,derogatory_marks,total_debt,loan_status
0,10700.0,7.672,52800,0.431818,5,1,22800,0
1,8400.0,6.692,43600,0.311927,3,0,13600,0
2,9000.0,6.963,46100,0.349241,3,0,16100,0
3,10700.0,7.664,52700,0.430740,5,1,22700,0
4,10800.0,7.698,53000,0.433962,5,1,23000,0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [3]:
y = lending_data_df["loan_status"]
X = lending_data_df.drop(columns="loan_status")

In [4]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [5]:
X.head()

,loan_size,interest_rate,borrower_income,debt_to_income,num_of_accounts,derogatory_marks,total_debt
0,10700.0,7.672,52800,0.431818,5,1,22800
1,8400.0,6.692,43600,0.311927,3,0,13600
2,9000.0,6.963,46100,0.349241,3,0,16100
3,10700.0,7.664,52700,0.430740,5,1,22700
4,10800.0,7.698,53000,0.433962,5,1,23000

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [6]:
y.value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

The split is stratified on `loan_status`, so the high-risk share (3.2%) is the same in both sets.

In [7]:
X_train, X_test, y_train, y_test = split(X, y)
pd.DataFrame({"train": y_train.value_counts(), "test": y_test.value_counts()})

             train   test
loan_status
0            56277  18759
1             1875    625

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

Features are standardized first; without scaling, the `lbfgs` solver does not converge on this data.

In [8]:
baseline = build_model().fit(X_train, y_train)
baseline

Pipeline(steps=[('scale', StandardScaler()),
                ('clf', LogisticRegression(random_state=1))])

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [9]:
baseline_results = evaluate(baseline, X_test, y_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [10]:
print(f"Balanced accuracy: {baseline_results['balanced_accuracy']:.3f}")

Balanced accuracy: 0.986

In [11]:
print(baseline_results["confusion_matrix"])

[[18669    90]
 [   14   611]]

In [12]:
print(baseline_results["report"])

              precision    recall  f1-score   support

     healthy      0.999     0.995     0.997     18759
   high-risk      0.872     0.978     0.922       625

    accuracy                          0.995     19384
   macro avg      0.935     0.986     0.959     19384
weighted avg      0.995     0.995     0.995     19384

### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** It does well for our healthy loans, but when it comes to our unhealthy loans, our predictions become less accurate. This is because of the difference in available data between our healthy and unhealthy loans: we have 18,759 data points for healthy loans in the test set but only 625 unhealthy loans. But as you can see, our model does well in both categories in our weighted average.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the training data to a 0.18 high-risk to healthy ratio.

In [13]:
X_over, y_over = RandomOverSampler(sampling_strategy=0.18, random_state=1).fit_resample(X_train, y_train)

In [14]:
y_over.value_counts()

loan_status
0    56277
1    10129
Name: count, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [15]:
# The pipeline applies the same oversampling internally, to the training data only
oversampled = build_model(oversample_ratio=0.18).fit(X_train, y_train)
oversampled_results = evaluate(oversampled, X_test, y_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [16]:
print(f"Balanced accuracy: {oversampled_results['balanced_accuracy']:.3f}")

Balanced accuracy: 0.994

In [17]:
print(oversampled_results["confusion_matrix"])

[[18668    91]
 [    5   620]]

In [18]:
print(oversampled_results["report"])

              precision    recall  f1-score   support

     healthy      1.000     0.995     0.997     18759
   high-risk      0.872     0.992     0.928       625

    accuracy                          0.995     19384
   macro avg      0.936     0.994     0.963     19384
weighted avg      0.996     0.995     0.995     19384

### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** Our oversampled model performs very similarly to the model trained on the original data. However, the difference here is that it does better on the unhealthy recall score, and yet our precision remains in the same range. Even though we oversample a lot more training data to train on, its ability to avoid false positives remains unchanged, as the number does not change, indicating we need more unhealthy data points for our training model, since random oversampling helps with the recall but does so by repeatedly copying the same unhealthy data points.